### ISSUE TITLE
Building problem

### ISSUE THREAD

**Issue by Schaeferjo** [Schaeferjo/advent_calendar#2]
I´m almoust done with the calendar. But i got a final problem: when I run yarn build, the result is an empty page.
Any idea?

**Comment by roschaefer** [comment]
I cannot reproduce the problem. I am on this commit:
```sh
$ git rev-parse HEAD
f82e29bb69ab1e3e4b9abc9e7e0202b7e2537e2b
```

And the app looks just fine:

![Screenshot - 2019-11-29T215318 409](https://user-images.githubusercontent.com/2110676/69889683-9d613300-12f2-11ea-9918-48675c6b5900.png)


:+1:

**Comment by roschaefer** [comment]
As discussed, when you compile javascript with `yarn run build` you **must** serve the `dist/` folder with a file server. E.g. `http-server dist/`.
